version: "3.8"
services:
  frontend:
    #build: ./frontend
    image: nstandev/frontend-service:1.0.2
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  backend:
    # build: ./backend
    image: nstandev/backend-service:1.0.2
    environment:
      DB_HOST: db
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  db:
    image: mariadb:10.6
    environment:
      MARIADB_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: mydatabase
      # MYSQL_USER: user
      # MYSQL_PASSWORD: password
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pyourpassword"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
