apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        #   value: db
        # - name: DB_USER
        #   value: user
        # - name: DB_PASSWORD
        #   value: password
        # - name: DB_NAME
        #   value: mydatabase

        # get enviromment variables from a configmap and secret
        envFrom:
        - configMapRef:
            name: backend-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: DB_PASSWORD

        